apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-jcr-data
  labels:
    {{- include "artifactory-jcr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
