version: '3.8'
name: archiva
services:
  postgres:
    image: postgres:16.2
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres/user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres/password
      - POSTGRES_DB_FILE=/run/secrets/postgres/db
      - POSTGRES_EXTRA_DBS_FILE=/run/secrets/postgres/extra_dbs
    shm_size: 128mb
    volumes:
      - ./secrets/dev/postgres/:/run/secrets/postgres
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$(cat /run/secrets/postgres/user)\" -d \"$(cat /run/secrets/postgres/db)\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  deployer:
    build:
      context: ./deployer
    volumes:
      - ./secrets/dev/git/url:/run/secrets/git/url
      - ./secrets/dev/artifactory/maven/id:/run/secrets/artifactory/maven/id
      - ./secrets/dev/artifactory/maven/url:/run/secrets/artifactory/maven/url
  artifactory-oss:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.84.14
    entrypoint: ["/opt/jfrog/artifactory/scripts/run.sh"]
    restart: always
    hostname: artifactory-oss
    environment:
      - NODE_ID=artifactory-oss
      - DATABASE_URL_FILE=/run/secrets/artifactory/oss/postgres/url
      - DATABASE_USERNAME_FILE=/run/secrets/postgres/user
      - DATABASE_PASSWORD_FILE=/run/secrets/postgres/password
    ports:
     - 18082:8082
    volumes:
      - ./artifactory/system-template.yaml:/opt/jfrog/artifactory/templates/system-template.yaml
      - ./artifactory/run.sh:/opt/jfrog/artifactory/scripts/run.sh
      - ./secrets/dev/artifactory/oss/security/master.key:/opt/jfrog/artifactory/var/etc/security/master.key
      - ./secrets/dev/artifactory/oss/security/join.key:/opt/jfrog/artifactory/var/etc/security/join.key
      - ./secrets/dev/artifactory/oss/postgres/url:/run/secrets/artifactory/oss/postgres/url
      - ./secrets/dev/postgres:/run/secrets/postgres
      - type: volume
        source: artifactory_oss
        target: /opt/jfrog/artifactory
    depends_on:
      postgres:
        condition: service_healthy
  artifactory-jcr:
    image: releases-docker.jfrog.io/jfrog/artifactory-jcr:7.84.14
    entrypoint: ["/opt/jfrog/artifactory/scripts/run.sh"]
    restart: always
    hostname: artifactory-jcr
    environment:
      - NODE_ID=artifactory-jcr
      - DATABASE_URL_FILE=/run/secrets/artifactory/jcr/postgres/url
      - DATABASE_USERNAME_FILE=/run/secrets/postgres/user
      - DATABASE_PASSWORD_FILE=/run/secrets/postgres/password
    ports:
     - 19092:8082
    volumes:
      - ./artifactory/system-template.yaml:/opt/jfrog/artifactory/templates/system-template.yaml
      - ./artifactory/run.sh:/opt/jfrog/artifactory/scripts/run.sh
      - ./secrets/dev/artifactory/jcr/security/master.key:/opt/jfrog/artifactory/var/etc/security/master.key
      - ./secrets/dev/artifactory/jcr/security/join.key:/opt/jfrog/artifactory/var/etc/security/join.key
      - ./secrets/dev/artifactory/jcr/postgres/url:/run/secrets/artifactory/jcr/postgres/url
      - ./secrets/dev/postgres:/run/secrets/postgres
      - type: volume
        source: artifactory_jcr
        target: /opt/jfrog/artifactory
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
  artifactory_oss:
  artifactory_jcr:
