apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-postgres-data
  labels:
    {{- include "artifactory-postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.dataPvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
  {{- range .Values.dataPvc.resources }}
    requests:
      {{- toYaml . | nindent 6 }}
  {{- end }}
