apiVersion: v1
kind: Service
metadata:
  name: {{ include "artifactory-postgres.fullname" . }}
  labels:
    {{- include "artifactory-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: artpgport
      protocol: TCP
      name: artpgport
  selector:
    {{- include "artifactory-postgres.selectorLabels" . | nindent 4 }}
