apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: artifactory-jcr
  name: artifactory-jcr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
