apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: artifactory-jcr
  name: artifactory-jcr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: artifactory-jcr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: artifactory-jcr
    spec:
      containers:
        - command:
            - /opt/jfrog/artifactory/scripts/run.sh
          image: releases-docker.jfrog.io/jfrog/artifactory-jcr:7.84.14
          name: artifactory-jcr
          ports:
            - containerPort: 8082
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/jfrog/artifactory/scripts/run.sh
              name: artifactory-jcr-entrypoint-cm
              subPath: run.sh
            - mountPath: /opt/jfrog/artifactory/var
              name: artifactory-jcr
            - mountPath: /run/secrets/artifactory/jcr
              name: artifactory-jcr-secret
      hostname: artifactory-jcr
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: run.sh
                path: run.sh
            name: artifactory-jcr-entrypoint-cm
            defaultMode: 0777
          name: artifactory-jcr-entrypoint-cm
        - name: artifactory-jcr
          persistentVolumeClaim:
            claimName: artifactory-jcr
        - secret:
            secretName: artifactory-jcr-secret
          name: artifactory-jcr-secret
  