apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: artifactory-postgres
  name: artifactory-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: artifactory-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: artifactory-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB_FILE
              value: /run/secrets/postgres/db
            - name: POSTGRES_EXTRA_DBS_FILE
              value: /run/secrets/postgres/extra-dbs
            - name: POSTGRES_PASSWORD_FILE
              value: /run/secrets/postgres/password
            - name: POSTGRES_USER_FILE
              value: /run/secrets/postgres/user
          image: postgres:16.2
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /run/scripts/postgres/is-ready.sh
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: artifactory-postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: artifactory-postgres-initdb-cm
            - mountPath: /run/scripts/postgres/is-ready.sh
              name: artifactory-postgres-probe-cm
              subPath: is-ready.sh
            - mountPath: /var/lib/postgresql/data
              name: artifactory-postgres-data
            - mountPath: /run/secrets/postgres
              name: artifactory-postgres-secret
              readOnly: true
      hostname: artifactory-postgres
      restartPolicy: Always
      volumes:
        - configMap:
            name: artifactory-postgres-initdb-cm
            defaultMode: 0777
          name: artifactory-postgres-initdb-cm
        - configMap:
            name: artifactory-postgres-probe-cm
            defaultMode: 0755
          name: artifactory-postgres-probe-cm
        - name: artifactory-postgres-data
          persistentVolumeClaim:
            claimName: artifactory-postgres-data
        - secret:
            secretName: artifactory-postgres-secret
          name: artifactory-postgres-secret
