apiVersion: v1
data:
  run.sh: |-
    #!/bin/bash

    set -eu

    copySecrets() {
      local artifactory_home=/opt/jfrog/artifactory

      mkdir -p ${artifactory_home}/var/etc/security

      cp /run/secrets/artifactory/oss/join.key ${artifactory_home}/var/etc/security/join.key
      cp /run/secrets/artifactory/oss/master.key ${artifactory_home}/var/etc/security/master.key

      cp /run/secrets/artifactory/oss/system.yaml ${artifactory_home}/var/etc/system.yaml

      chown -R "${JF_ARTIFACTORY_USER}":"${JF_ARTIFACTORY_USER}" ${artifactory_home}/var
    }

    copySecrets
    /entrypoint-artifactory.sh
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: artifactory-oss
  name: artifactory-oss-entrypoint-cm
