apiVersion: v1
kind: Service
metadata:
  name: {{ include "artifactory-oss.fullname" . }}
  labels:
    {{- include "artifactory-oss.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: artossport
      protocol: TCP
      name: artossport
  selector:
    {{- include "artifactory-oss.selectorLabels" . | nindent 4 }}
